name: Deploy to server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Clean node_modules on server
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/id_rsa \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "cd ${{ secrets.SERVER_PATH }} && rm -rf node_modules"

      - name: Upload files
        run: |
          rsync -avz --delete --exclude='.git/' --exclude='node_modules/' --exclude='vendor/' \
            --exclude='.github/' --exclude='public/.user.ini' --exclude='.env' \
            --stats --timeout=120 \
            -e "ssh -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/id_rsa" \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}

      - name: Install node dependencies
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/id_rsa \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "cd ${{ secrets.SERVER_PATH }} && npm install"

      - name: Install composer dependencies
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/id_rsa \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "cd ${{ secrets.SERVER_PATH }} && export COMPOSER_ALLOW_SUPERUSER=1 && composer install --no-dev --optimize-autoloader"

      - name: Build assets
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/id_rsa \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "cd ${{ secrets.SERVER_PATH }} && npm run build"

      - name: Run database migrations
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/id_rsa \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "cd ${{ secrets.SERVER_PATH }} && yes | php artisan migrate"

      - name: Update ownership to www
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/id_rsa \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "chown -R www:www ${{ secrets.SERVER_PATH }}"

      - name: Update permissions 775 for directories and 644 for files
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/id_rsa \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "find ${{ secrets.SERVER_PATH }} -type d -exec chmod 775 {} \; && find ${{ secrets.SERVER_PATH }} -type f -not -path \"***/public/.user.ini\" -exec chmod 644 {} \;"
